wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.7.9
      5: 0.10.15
      8:
      - 1
